name: Deploy to MijnDomein

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy site via SFTP
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to MijnDomein
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: './'
          server-dir: './'
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
